HUGE commit!
Please read the NEWS file for details regarding this commit.
All changes in this commit are availble on 1.6.4-alpha3 codename 'Indiana Jones'

diff --git a/scripts/initrd b/scripts/initrd
--- a/scripts/initrd
+++ b/scripts/initrd
@@ -2,6 +2,11 @@
 
 . /etc/lunar/config
 
+if [ -e /proc/modules ] && ! grep -qs "loop" /proc/devices; then
+  modprobe loop
+  grep -qs loop /proc/devices || echo "Bailing out, "loop" driver is missing"
+fi
+
 cd $ISO_SOURCE/initrd
 
 umount $ISO_TARGET/dev &> /dev/null
@@ -14,7 +19,7 @@ rm -rf BUILD
 # template first
 cp -a --no-dereference template BUILD
 find BUILD -type d -name '.svn' -exec rm -rf {} \; >/dev/null 2>&1
-mkdir -p BUILD/{mnt,proc,var/lib/discover,usr}
+mkdir -p BUILD/{mnt/cdrom,mnt/device,proc,var/lib/discover,usr}
 if [ "$ISO_KSUFFIX" == "2.6" ]; then
 	mkdir BUILD/sys
 fi
@@ -44,6 +49,15 @@ transfer()
 	cat $ISO_SOURCE/initrd/initrd.list-$ISO_KSUFFIX | transfer
 	$ISO_SOURCE/scripts/ldd-gather $ISO_SOURCE/initrd/initrd.list | transfer
 	$ISO_SOURCE/scripts/ldd-gather $ISO_SOURCE/initrd/initrd.list-$ISO_KSUFFIX | transfer
+)
+
+echo "+ copying and setting up udev rules"
+(
+  cd $ISO_TARGET
+  cp --no-dereference -r etc/udev $ISO_SOURCE/initrd/BUILD/etc/
+  for i in $ISO_SOURCE/initrd/BUILD/etc/udev/rules.d/*; do
+    sed -i 's;GROUP=".*";;g' $i
+  done
 )
 
 
@@ -91,8 +105,11 @@ for KERNEL in linux safe ; do
     cd TMP
     tar xjf $ISO_SOURCE/kernels/TAR/$KVER.tar.bz2
     mkdir -p $ISO_SOURCE/initrd/BUILD/lib/modules/$KVER/kernel/drivers/
+    mkdir -p $ISO_SOURCE/initrd/BUILD/lib/modules/$KVER/kernel/fs/
     echo "+ cp -a --no-dereference lib/modules/$KVER/kernel/drivers/{block,md,ata,ide,scsi,usb/host} $ISO_SOURCE/initrd/BUILD/lib/modules/$KVER/kernel/drivers/"
     cp -a --no-dereference lib/modules/$KVER/kernel/drivers/{block,md,ata,ide,scsi,usb/host} $ISO_SOURCE/initrd/BUILD/lib/modules/$KVER/kernel/drivers/
+    echo "+ cp -a --no-dereference lib/modules/$KVER/kernel/drivers/fs/{nls,fat,vfat,reiserfs,xfs,ext4} $ISO_SOURCE/initrd/BUILD/lib/modules/$KVER/kernel/fs/"
+    cp -a --no-dereference lib/modules/$KVER/kernel/fs/{nls,fat,vfat,reiserfs,xfs,ext4} $ISO_SOURCE/initrd/BUILD/lib/modules/$KVER/kernel/fs/
     echo "+ cp lib/modules/$KVER/modules.* $ISO_SOURCE/initrd/BUILD/lib/modules/$KVER/"
     cp lib/modules/$KVER/* $ISO_SOURCE/initrd/BUILD/lib/modules/$KVER/
     echo "+ depmod -b $ISO_SOURCE/initrd/BUILD -a -F $ISO_SOURCE/kernels/$KERNEL.map $KVER"
@@ -110,7 +127,7 @@ for ITEM in $(find BUILD -type d -name ".svn" | tac); do
 done
 
 chown -R root:root BUILD/*
-  
+
 echo "+ running ldconfig"
 chroot BUILD /sbin/ldconfig &&
 rm -f BUILD/etc/mtab &&
@@ -127,7 +144,7 @@ sed "s/INITRDSIZE/$SIZE/g" $ISO_SOURCE/isolinux/isolinux.cfg.in > $ISO_SOURCE/is
 
 dd if=/dev/zero of=initrd.raw bs=1024 count=$SIZE &&
 losetup /dev/loop/0 initrd.raw &&
-mkfs.ext2 -b 1024 -m 0 -i 1024 -N 512 /dev/loop/0 &&
+mkfs.ext2 -b 1024 -m 0 -i 1024 -N 768 /dev/loop/0 &&
 mkdir BUILD.mnt &&
 mount /dev/loop/0 BUILD.mnt &&
 cp -a BUILD/* BUILD.mnt/ &&
diff --git a/scripts/isofs b/scripts/isofs
--- a/scripts/isofs
+++ b/scripts/isofs
@@ -2,6 +2,13 @@
 
 . /etc/lunar/config
 
+echo "+ Checking if cdrtools is installed"
+if ! lsh module_installed cdrtools; then
+  echo "Cdrtools missing: installing..."
+  lin -c cdrtools
+  lsh module_installed cdrtools || exit 1
+fi
+
 echo "+ tagging release version"
 echo "Lunar Linux $ISO_CNAME" > $ISO_TARGET/etc/lunar.release
 echo "lunar" > $ISO_TARGET/etc/hostname
@@ -47,13 +54,16 @@ cp $ISO_SOURCE/template/README $ISO_TARGET
 echo "+ copying motd"
 cp $ISO_SOURCE/template/motd $ISO_TARGET/etc/
 cp $ISO_SOURCE/template/motd.target $ISO_TARGET/etc/
+echo "+ copying initd disable list"
+cp $ISO_SOURCE/conf/initd.disable.list $ISO_TARGET/.initd.disable.list
 
 for file in $ISO_TARGET/isolinux/{f{1,2,3,4}.txt,boot.cat,isolinux.{bin,cfg}} $ISO_TARGET/etc/motd $ISO_TARGET/etc/motd $ISO_TARGET/sbin/lunar-install $ISO_TARGET/README $ISO_TARGET/etc/motd $ISO_TARGET/etc/motd.target ; do
   sed -i -e "s:%VERSION%:${ISO_VERSION}:g" \
          -e "s:%CODENAME%:${ISO_CODENAME}:g" \
          -e "s:%DATE%:${ISO_DATE}:g" \
          -e "s:%KERNEL%:${ISO_PVER}:g" \
-	 -e "s:%CNAME%:${ISO_CNAME}:g" $file
+	 -e "s:%CNAME%:${ISO_CNAME}:g" \
+	 -e "s:%COPYRIGHTYEAR%:${ISO_DATE:0:4}:g" $file
 done
 
 # reverse approach this:
diff --git a/scripts/rebuild b/scripts/rebuild
--- a/scripts/rebuild
+++ b/scripts/rebuild
@@ -19,23 +19,57 @@ export BOOTLOADER=none
 
 mkdir -p $ISO_TARGET/usr/src/
 
-mount -t proc proc $ISO_TARGET/proc
+# Lets get a full-featured environment FIXME: No failsafes!
+function mount_system_fs ()
+{
+  echo "$ISO_TARGET"
+  for mpoint in proc sys dev ; do
+    mount --bind /${mpoint} $ISO_TARGET/${mpoint} &> /dev/null
+  done
+}
+
+function umount_system_fs ()
+{
+  for mpoint in proc sys dev ; do
+    if ! umount $ISO_TARGET/${mpoint} &> /dev/null ; then
+      umount -l -f $ISO_TARGET/${mpoint} &> /dev/null
+    fi
+  done
+}
+
+# iptables needs the current kernel sources
+function compile_iptables ()
+{
+  echo "Setting up kernel directory"
+  mkdir -p $ISO_TARGET/usr/src/linux
+  mount --bind /usr/src/linux $ISO_TARGET/usr/src/linux
+
+  echo "Compiling iptables"
+  chroot $ISO_TARGET /sbin/lin -c iptables
+
+  echo "Resetting kernel directory"
+  umount $ISO_TARGET/usr/src/linux
+  rm -rf $ISO_TARGET/usr/src/linux
+}
 
 echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 echo "+          STARTING CONFIGURING MODULES                +"
 echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 echo ""
 
-for mod in $(cat conf/base.list conf/base.list-${ISO_KSUFFIX} conf/extended.list) ; do
-  yes '' | NEVER_ASK=y chroot $ISO_TARGET /sbin/lin --deps $mod
+mount_system_fs &&
+
+# We have no dependency cache or status file
+echo "Creating preliminary dependency index and cache"
+chroot $ISO_TARGET lsh create_module_index
+chroot $ISO_TARGET lsh create_depends_cache
+#exit 0
+# glibc is special
+chroot $ISO_TARGET /sbin/lin --deps --reconfigure glibc
+
+for mod in $(cat conf/base.list conf/base.list-${ISO_KSUFFIX} conf/extended.list | grep -v glibc | grep -v perl) ; do
+  yes '' | NEVER_ASK=y chroot $ISO_TARGET /sbin/lin --deps --reconfigure $mod
 done
-
-umount $ISO_TARGET/proc &> /dev/null
-chroot $ISO_TARGET lin makedev
-mount -t proc proc $ISO_TARGET/proc
-
-chroot $ISO_TARGET /dev/install-devices.sh
-chroot $ISO_TARGET rm -rf /var/build/makedev-*
 
 case ${ISO_KSUFFIX} in
 	2.4)
@@ -46,7 +80,7 @@ case ${ISO_KSUFFIX} in
 		;;
 esac
 
-chroot $ISO_TARGET lin kernel-headers-${ISO_KSUFFIX}
+chroot $ISO_TARGET /sbin/lin kernel-headers-${ISO_KSUFFIX}
 
 # install core tools manually, since we can't download
 
@@ -57,11 +91,23 @@ echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 echo ""
 
 # perl is notoriously problematic and needs to be built before glibc
-chroot $ISO_TARGET lin perl
+chroot $ISO_TARGET /sbin/lin -c perl
+chroot $ISO_TARGET /sbin/lin -c glibc
+chroot $ISO_TARGET /sbin/lin -c gcc
 
-for mod in $(cat conf/base.list conf/base.list-${ISO_KSUFFIX} conf/extended.list) ; do
-  chroot $ISO_TARGET /sbin/lin -c $mod
+# Compile everything but iptables (see next paragraph)
+for mod in `lsh sort_by_dependency $(cat conf/base.list conf/base.list-${ISO_KSUFFIX} conf/extended.list | grep -v iptables)` ; do
+  if [ "$mod" == "glibc" ]; then
+    # Remove bits/syscall.h or it will be missing on the iso
+    rm -f $ISO_TARGET/usr/include/bits/syscall.h
+    chroot $ISO_TARGET /sbin/lin -c $mod
+  else
+    chroot $ISO_TARGET /sbin/lin -c $mod
+  fi
 done
+
+# We need to setup a special environment for iptables to compile in
+compile_iptables &&
 
 # openssh installs ssh keys so these are now tracked in the module :^(
 chroot $ISO_TARGET /sbin/lin -c openssh
@@ -78,7 +124,6 @@ echo "Broken compiles:"
 (cd $ISO_TARGET/usr/src/ && ls -1)
 echo ""
 
-umount $ISO_TARGET/proc
+umount_system_fs &&
 
 touch $ISO_TARGET/.rebuild
-
