Fix "missing" lunar - the packages file had the wrong version number. ugh. Added test target to make sure it works.

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 [ ! -f $ISO_TARGET/var/lib/lunar/moonbase.tar.bz2 ] && echo "FAIL: missing moonbase" && exit 1
-[ ! -f $ISO_TARGET/var/cache/lunar/$ISO_LUNAR_MODULE-$ISO_DATE-$ISO_BUILD.tar.bz2 ] && echo "FAIL: missing $ISO_LUNAR_MODULE" && exit 1
-grep -q "^$ISO_LUNAR_MODULE:$ISO_DATE:" $ISO_TARGET/.packages || ( echo "FAIL: missing $ISO_LUNAR_MODULE in package list" && exit 1)
+[ ! -f $ISO_TARGET/var/cache/lunar/$ISO_LUNAR_MODULE-$(lsh module_version $ISO_LUNAR_MODULE)-$ISO_BUILD.tar.bz2 ] && echo "FAIL: missing $ISO_LUNAR_MODULE" && exit 1
+grep -q "^$ISO_LUNAR_MODULE:$(lsh module_version $ISO_LUNAR_MODULE):" $ISO_TARGET/.packages || ( echo "FAIL: missing $ISO_LUNAR_MODULE in package list" && exit 1)
 
 if [ -f $ISO_TARGET/.rebuild ]; then
 	# first define the tests:
@@ -36,6 +36,13 @@ if [ -f $ISO_TARGET/.rebuild ]; then
 			echo "OK"
 		else
 			echo "FAILED"
+			RESULT=1
+		fi
+	done
+	for M in $(cat conf/base.list conf/extended.list conf/base.list-$ISO_KSUFFIX); do
+		V=$(grep "^$M:" $ISO_TARGET/.packages | cut -d: -f4 | tail -n 1)
+		if [ ! -f "$ISO_TARGET/var/cache/lunar/$M-$V-$ISO_BUILD.tar.bz2" ]; then
+			echo "FAILED: Cache is missing: $M-$V-$ISO_BUILD.tar.bz2"
 			RESULT=1
 		fi
 	done
