Another adjustment here, same bug.

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -2,7 +2,7 @@
 
 [ ! -f $ISO_TARGET/var/lib/lunar/moonbase.tar.bz2 ] && echo "FAIL: missing moonbase" && exit 1
 [ ! -f $ISO_TARGET/var/cache/lunar/$ISO_LUNAR_MODULE-$(lsh module_version $ISO_LUNAR_MODULE)-$ISO_BUILD.tar.bz2 ] && echo "FAIL: missing $ISO_LUNAR_MODULE" && exit 1
-grep -q "^$ISO_LUNAR_MODULE:$(lsh module_version $ISO_LUNAR_MODULE):" $ISO_TARGET/.packages || ( echo "FAIL: missing $ISO_LUNAR_MODULE in package list" && exit 1)
+grep -q "^$ISO_LUNAR_MODULE:........:installed:$(lsh module_version $ISO_LUNAR_MODULE):" $ISO_TARGET/.packages || ( echo "FAIL: missing $ISO_LUNAR_MODULE in package list" && exit 1)
 
 if [ -f $ISO_TARGET/.rebuild ]; then
 	# first define the tests:
